VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
CAPS_WORD_ENABLE = yes

QMK_SETTINGS = yes
LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
